// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctors.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctorProfile = `-- name: CreateDoctorProfile :exec
INSERT INTO doctor_profiles (user_id, first_name, last_name, specialty, experience_years, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDoctorProfileParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	Specialty       pgtype.Text `json:"specialty"`
	ExperienceYears pgtype.Int4 `json:"experience_years"`
	TenantID        uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) CreateDoctorProfile(ctx context.Context, arg CreateDoctorProfileParams) error {
	_, err := q.db.Exec(ctx, createDoctorProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Specialty,
		arg.ExperienceYears,
		arg.TenantID,
	)
	return err
}

const createDoctorUser = `-- name: CreateDoctorUser :one
INSERT INTO users (email, hashed_password, role, tenant_id)
VALUES ($1, $2, 'doctor', $3)
RETURNING id
`

type CreateDoctorUserParams struct {
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CreateDoctorUser(ctx context.Context, arg CreateDoctorUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDoctorUser, arg.Email, arg.HashedPassword, arg.TenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDoctorByEmail = `-- name: GetDoctorByEmail :one
SELECT u.id, u.email, d.first_name, d.last_name, d.specialty, d.experience_years, d.available, u.hashed_password, u.role, u.created_at
FROM users u
JOIN doctor_profiles d ON u.id = d.user_id
WHERE u.email = $1 AND u.role = 'doctor' AND u.is_active = true AND u.tenant_id = $2
`

type GetDoctorByEmailParams struct {
	Email    string    `json:"email"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDoctorByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Specialty       pgtype.Text        `json:"specialty"`
	ExperienceYears pgtype.Int4        `json:"experience_years"`
	Available       pgtype.Bool        `json:"available"`
	HashedPassword  string             `json:"hashed_password"`
	Role            string             `json:"role"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDoctorByEmail(ctx context.Context, arg GetDoctorByEmailParams) (GetDoctorByEmailRow, error) {
	row := q.db.QueryRow(ctx, getDoctorByEmail, arg.Email, arg.TenantID)
	var i GetDoctorByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Specialty,
		&i.ExperienceYears,
		&i.Available,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT u.id, u.email, d.first_name, d.last_name, d.specialty, d.experience_years, d.available, u.created_at
FROM users u
JOIN doctor_profiles d ON u.id = d.user_id
WHERE u.id = $1 AND u.role = 'doctor' AND u.is_active = true AND u.tenant_id = $2
`

type GetDoctorByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDoctorByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Specialty       pgtype.Text        `json:"specialty"`
	ExperienceYears pgtype.Int4        `json:"experience_years"`
	Available       pgtype.Bool        `json:"available"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDoctorByID(ctx context.Context, arg GetDoctorByIDParams) (GetDoctorByIDRow, error) {
	row := q.db.QueryRow(ctx, getDoctorByID, arg.ID, arg.TenantID)
	var i GetDoctorByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Specialty,
		&i.ExperienceYears,
		&i.Available,
		&i.CreatedAt,
	)
	return i, err
}

const getDoctors = `-- name: GetDoctors :many
SELECT u.id, u.email, d.first_name, d.last_name, d.specialty, d.experience_years, d.available, u.created_at
FROM users u
JOIN doctor_profiles d ON u.id = d.user_id
WHERE u.role = 'doctor' AND u.is_active = true AND u.tenant_id = $3
ORDER BY d.first_name ASC, u.id ASC
LIMIT $1 OFFSET $2
`

type GetDoctorsParams struct {
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDoctorsRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Specialty       pgtype.Text        `json:"specialty"`
	ExperienceYears pgtype.Int4        `json:"experience_years"`
	Available       pgtype.Bool        `json:"available"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDoctors(ctx context.Context, arg GetDoctorsParams) ([]GetDoctorsRow, error) {
	rows, err := q.db.Query(ctx, getDoctors, arg.Limit, arg.Offset, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDoctorsRow{}
	for rows.Next() {
		var i GetDoctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
			&i.ExperienceYears,
			&i.Available,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
