// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ocr.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createOCRProviderConfig = `-- name: CreateOCRProviderConfig :one
INSERT INTO ocr_provider_configs (
    tenant_id,
    provider_name,
    encrypted_key,
    nonce
) VALUES (
    $1, $2, $3, $4
) RETURNING id, tenant_id, provider_name, encrypted_key, nonce, created_at, updated_at
`

type CreateOCRProviderConfigParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProviderName string    `json:"provider_name"`
	EncryptedKey []byte    `json:"encrypted_key"`
	Nonce        []byte    `json:"nonce"`
}

func (q *Queries) CreateOCRProviderConfig(ctx context.Context, arg CreateOCRProviderConfigParams) (OcrProviderConfig, error) {
	row := q.db.QueryRow(ctx, createOCRProviderConfig,
		arg.TenantID,
		arg.ProviderName,
		arg.EncryptedKey,
		arg.Nonce,
	)
	var i OcrProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderName,
		&i.EncryptedKey,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOCRProviderConfig = `-- name: DeleteOCRProviderConfig :exec
DELETE FROM ocr_provider_configs
WHERE id = $1 AND tenant_id = $2
`

type DeleteOCRProviderConfigParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteOCRProviderConfig(ctx context.Context, arg DeleteOCRProviderConfigParams) error {
	_, err := q.db.Exec(ctx, deleteOCRProviderConfig, arg.ID, arg.TenantID)
	return err
}

const getOCRProviderConfigByID = `-- name: GetOCRProviderConfigByID :one
SELECT id, tenant_id, provider_name, encrypted_key, nonce, created_at, updated_at FROM ocr_provider_configs
WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetOCRProviderConfigByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetOCRProviderConfigByID(ctx context.Context, arg GetOCRProviderConfigByIDParams) (OcrProviderConfig, error) {
	row := q.db.QueryRow(ctx, getOCRProviderConfigByID, arg.ID, arg.TenantID)
	var i OcrProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderName,
		&i.EncryptedKey,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOCRProviderConfigsByIDs = `-- name: GetOCRProviderConfigsByIDs :many
SELECT id, tenant_id, provider_name, encrypted_key, nonce, created_at, updated_at FROM ocr_provider_configs
WHERE id = ANY($1::uuid[]) AND tenant_id = $2
`

type GetOCRProviderConfigsByIDsParams struct {
	Column1  []uuid.UUID `json:"column_1"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) GetOCRProviderConfigsByIDs(ctx context.Context, arg GetOCRProviderConfigsByIDsParams) ([]OcrProviderConfig, error) {
	rows, err := q.db.Query(ctx, getOCRProviderConfigsByIDs, arg.Column1, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OcrProviderConfig{}
	for rows.Next() {
		var i OcrProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderName,
			&i.EncryptedKey,
			&i.Nonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOCRProviderConfigsForTenant = `-- name: GetOCRProviderConfigsForTenant :many
SELECT id, tenant_id, provider_name, encrypted_key, nonce, created_at, updated_at FROM ocr_provider_configs
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOCRProviderConfigsForTenant(ctx context.Context, tenantID uuid.UUID) ([]OcrProviderConfig, error) {
	rows, err := q.db.Query(ctx, getOCRProviderConfigsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OcrProviderConfig{}
	for rows.Next() {
		var i OcrProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderName,
			&i.EncryptedKey,
			&i.Nonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT tenant_id, ocr_fallback_chain, updated_at FROM tenant_settings
WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetTenantSettings(ctx context.Context, tenantID uuid.UUID) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, tenantID)
	var i TenantSetting
	err := row.Scan(&i.TenantID, &i.OcrFallbackChain, &i.UpdatedAt)
	return i, err
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO tenant_settings (
    tenant_id,
    ocr_fallback_chain,
    updated_at
) VALUES (
    $1, $2, now()
)
ON CONFLICT (tenant_id) DO UPDATE 
SET ocr_fallback_chain = EXCLUDED.ocr_fallback_chain,
    updated_at = now()
RETURNING tenant_id, ocr_fallback_chain, updated_at
`

type UpsertTenantSettingsParams struct {
	TenantID         uuid.UUID   `json:"tenant_id"`
	OcrFallbackChain []uuid.UUID `json:"ocr_fallback_chain"`
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSettings, arg.TenantID, arg.OcrFallbackChain)
	var i TenantSetting
	err := row.Scan(&i.TenantID, &i.OcrFallbackChain, &i.UpdatedAt)
	return i, err
}
