// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientProfile = `-- name: CreatePatientProfile :exec
INSERT INTO patient_profiles (user_id, first_name, last_name, tenant_id)
VALUES ($1, $2, $3, $4)
`

type CreatePatientProfileParams struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) error {
	_, err := q.db.Exec(ctx, createPatientProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.TenantID,
	)
	return err
}

const createPatientUser = `-- name: CreatePatientUser :one
INSERT INTO users (email, hashed_password, role, tenant_id)
VALUES ($1, $2, 'patient', $3)
RETURNING id
`

type CreatePatientUserParams struct {
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CreatePatientUser(ctx context.Context, arg CreatePatientUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPatientUser, arg.Email, arg.HashedPassword, arg.TenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPatientByEmail = `-- name: GetPatientByEmail :one
SELECT u.id, u.email, p.first_name, p.last_name, u.hashed_password, u.tenant_id, u.created_at
FROM users u
JOIN patient_profiles p ON u.id = p.user_id
WHERE u.email = $1 AND u.role = 'patient' AND u.is_active = true AND u.tenant_id = $2
`

type GetPatientByEmailParams struct {
	Email    string    `json:"email"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetPatientByEmailRow struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	HashedPassword string             `json:"hashed_password"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPatientByEmail(ctx context.Context, arg GetPatientByEmailParams) (GetPatientByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPatientByEmail, arg.Email, arg.TenantID)
	var i GetPatientByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT u.id, u.email, p.first_name, p.last_name, u.tenant_id, u.created_at
FROM users u
JOIN patient_profiles p ON u.id = p.user_id
WHERE u.id = $1 AND u.role = 'patient' AND u.is_active = true AND u.tenant_id = $2
`

type GetPatientByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetPatientByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPatientByID(ctx context.Context, arg GetPatientByIDParams) (GetPatientByIDRow, error) {
	row := q.db.QueryRow(ctx, getPatientByID, arg.ID, arg.TenantID)
	var i GetPatientByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const getPatientsByDoctorID = `-- name: GetPatientsByDoctorID :many
SELECT u.id, u.email, p.first_name, p.last_name, u.tenant_id, u.created_at
FROM users u
JOIN patient_profiles p ON u.id = p.user_id
WHERE u.role = 'patient'
  AND u.is_active = true
  AND u.tenant_id = $4
  AND EXISTS (
      SELECT 1 FROM appointments a
      WHERE a.patient_id = u.id AND a.doctor_id = $1
  )
ORDER BY u.created_at DESC, u.id DESC
LIMIT $2 OFFSET $3
`

type GetPatientsByDoctorIDParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetPatientsByDoctorIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Uses an EXISTS semi-join instead of SELECT DISTINCT to avoid a full
// hash-aggregate/deduplication pass over all appointment rows.
// The EXISTS subquery short-circuits at the first matching appointment
// per patient, allowing PostgreSQL to use an index scan with pagination.
func (q *Queries) GetPatientsByDoctorID(ctx context.Context, arg GetPatientsByDoctorIDParams) ([]GetPatientsByDoctorIDRow, error) {
	rows, err := q.db.Query(ctx, getPatientsByDoctorID,
		arg.DoctorID,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatientsByDoctorIDRow{}
	for rows.Next() {
		var i GetPatientsByDoctorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.TenantID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasDoctorPatientRelationship = `-- name: HasDoctorPatientRelationship :one
SELECT (
    EXISTS (SELECT 1 FROM appointments a WHERE a.doctor_id = $1 AND a.patient_id = $2 AND a.status != 'cancelled' AND a.tenant_id = $3)
    OR
    EXISTS (SELECT 1 FROM prescriptions p WHERE p.doctor_id = $1 AND p.patient_id = $2 AND p.tenant_id = $3)
) AS has_relationship
`

type HasDoctorPatientRelationshipParams struct {
	DoctorID  uuid.UUID `json:"doctor_id"`
	PatientID uuid.UUID `json:"patient_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) HasDoctorPatientRelationship(ctx context.Context, arg HasDoctorPatientRelationshipParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, hasDoctorPatientRelationship, arg.DoctorID, arg.PatientID, arg.TenantID)
	var has_relationship pgtype.Bool
	err := row.Scan(&has_relationship)
	return has_relationship, err
}
