// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelAppointmentByParticipant(ctx context.Context, arg CancelAppointmentByParticipantParams) (int64, error)
	CheckPrescriptionFileNameExists(ctx context.Context, arg CheckPrescriptionFileNameExistsParams) (bool, error)
	CreateAdminProfile(ctx context.Context, arg CreateAdminProfileParams) error
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (uuid.UUID, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (uuid.UUID, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error)
	CreateDigitalPrescription(ctx context.Context, arg CreateDigitalPrescriptionParams) (uuid.UUID, error)
	CreateDoctorProfile(ctx context.Context, arg CreateDoctorProfileParams) error
	CreateDoctorUser(ctx context.Context, arg CreateDoctorUserParams) (uuid.UUID, error)
	CreateOCRProviderConfig(ctx context.Context, arg CreateOCRProviderConfigParams) (OcrProviderConfig, error)
	CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) error
	CreatePatientUser(ctx context.Context, arg CreatePatientUserParams) (uuid.UUID, error)
	CreatePatientVital(ctx context.Context, arg CreatePatientVitalParams) (CreatePatientVitalRow, error)
	CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (uuid.UUID, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	DeleteDoctorScheduleByDay(ctx context.Context, arg DeleteDoctorScheduleByDayParams) error
	DeleteOCRProviderConfig(ctx context.Context, arg DeleteOCRProviderConfigParams) error
	DeletePrescriptionItems(ctx context.Context, arg DeletePrescriptionItemsParams) error
	GetActivePrescriptionItemsForPatient(ctx context.Context, arg GetActivePrescriptionItemsForPatientParams) ([]GetActivePrescriptionItemsForPatientRow, error)
	GetAdminByEmail(ctx context.Context, arg GetAdminByEmailParams) (GetAdminByEmailRow, error)
	GetAdminByID(ctx context.Context, arg GetAdminByIDParams) (GetAdminByIDRow, error)
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]GetAllUsersRow, error)
	GetAppointmentByID(ctx context.Context, arg GetAppointmentByIDParams) (GetAppointmentByIDRow, error)
	GetAppointmentsByDoctorID(ctx context.Context, arg GetAppointmentsByDoctorIDParams) ([]GetAppointmentsByDoctorIDRow, error)
	GetAppointmentsByPatientID(ctx context.Context, arg GetAppointmentsByPatientIDParams) ([]GetAppointmentsByPatientIDRow, error)
	GetAppointmentsForPatient(ctx context.Context, arg GetAppointmentsForPatientParams) ([]GetAppointmentsForPatientRow, error)
	GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]GetAuditLogsRow, error)
	GetAuditLogsByPatientID(ctx context.Context, arg GetAuditLogsByPatientIDParams) ([]GetAuditLogsByPatientIDRow, error)
	GetDoctorAppointmentsInRange(ctx context.Context, arg GetDoctorAppointmentsInRangeParams) ([]GetDoctorAppointmentsInRangeRow, error)
	GetDoctorByEmail(ctx context.Context, arg GetDoctorByEmailParams) (GetDoctorByEmailRow, error)
	GetDoctorByID(ctx context.Context, arg GetDoctorByIDParams) (GetDoctorByIDRow, error)
	GetDoctorScheduleByDay(ctx context.Context, arg GetDoctorScheduleByDayParams) (GetDoctorScheduleByDayRow, error)
	GetDoctorSchedules(ctx context.Context, arg GetDoctorSchedulesParams) ([]GetDoctorSchedulesRow, error)
	GetDoctors(ctx context.Context, arg GetDoctorsParams) ([]GetDoctorsRow, error)
	GetLatestPatientVital(ctx context.Context, arg GetLatestPatientVitalParams) (GetLatestPatientVitalRow, error)
	GetMedicationLogsByDate(ctx context.Context, arg GetMedicationLogsByDateParams) ([]GetMedicationLogsByDateRow, error)
	GetOCRProviderConfigByID(ctx context.Context, arg GetOCRProviderConfigByIDParams) (OcrProviderConfig, error)
	GetOCRProviderConfigsByIDs(ctx context.Context, arg GetOCRProviderConfigsByIDsParams) ([]OcrProviderConfig, error)
	GetOCRProviderConfigsForTenant(ctx context.Context, tenantID uuid.UUID) ([]OcrProviderConfig, error)
	GetPatientByEmail(ctx context.Context, arg GetPatientByEmailParams) (GetPatientByEmailRow, error)
	GetPatientByID(ctx context.Context, arg GetPatientByIDParams) (GetPatientByIDRow, error)
	GetPatientVitals(ctx context.Context, arg GetPatientVitalsParams) ([]GetPatientVitalsRow, error)
	// Uses an EXISTS semi-join instead of SELECT DISTINCT to avoid a full
	// hash-aggregate/deduplication pass over all appointment rows.
	// The EXISTS subquery short-circuits at the first matching appointment
	// per patient, allowing PostgreSQL to use an index scan with pagination.
	GetPatientsByDoctorID(ctx context.Context, arg GetPatientsByDoctorIDParams) ([]GetPatientsByDoctorIDRow, error)
	GetPrescriptionByFilename(ctx context.Context, arg GetPrescriptionByFilenameParams) (GetPrescriptionByFilenameRow, error)
	GetPrescriptionByFilenameForDoctor(ctx context.Context, arg GetPrescriptionByFilenameForDoctorParams) (GetPrescriptionByFilenameForDoctorRow, error)
	GetPrescriptionByID(ctx context.Context, arg GetPrescriptionByIDParams) (GetPrescriptionByIDRow, error)
	GetPrescriptionItemsByPrescriptionID(ctx context.Context, arg GetPrescriptionItemsByPrescriptionIDParams) ([]GetPrescriptionItemsByPrescriptionIDRow, error)
	GetPrescriptionItemsByPrescriptionIDs(ctx context.Context, arg GetPrescriptionItemsByPrescriptionIDsParams) ([]GetPrescriptionItemsByPrescriptionIDsRow, error)
	GetPrescriptionsByPatientID(ctx context.Context, arg GetPrescriptionsByPatientIDParams) ([]GetPrescriptionsByPatientIDRow, error)
	GetPrescriptionsForPatient(ctx context.Context, arg GetPrescriptionsForPatientParams) ([]GetPrescriptionsForPatientRow, error)
	// Rewritten from OR EXISTS to a UNION of two targeted range scans.
	// Branch 1: direct doctor ownership — uses idx_prescriptions_needs_review
	//           (doctor_id, created_at DESC WHERE status = 'needs_review').
	// Branch 2: relationship via non-cancelled appointment — uses idx_appointments_patient_doctor_status.
	// Each branch independently uses its covering index; the UNION deduplicates.
	GetPrescriptionsPendingReview(ctx context.Context, arg GetPrescriptionsPendingReviewParams) ([]GetPrescriptionsPendingReviewRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTenantSettings(ctx context.Context, tenantID uuid.UUID) (TenantSetting, error)
	HasDoctorPatientRelationship(ctx context.Context, arg HasDoctorPatientRelationshipParams) (pgtype.Bool, error)
	InsertPrescriptionItem(ctx context.Context, arg InsertPrescriptionItemParams) (InsertPrescriptionItemRow, error)
	LockRefreshTokenForRotation(ctx context.Context, arg LockRefreshTokenForRotationParams) (RefreshToken, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	UpdateAppointmentAsCompletedForDoctor(ctx context.Context, arg UpdateAppointmentAsCompletedForDoctorParams) (int64, error)
	UpdateAppointmentMeetingRoom(ctx context.Context, arg UpdateAppointmentMeetingRoomParams) (int64, error)
	UpdatePrescriptionExpiry(ctx context.Context, arg UpdatePrescriptionExpiryParams) error
	UpdatePrescriptionFileName(ctx context.Context, arg UpdatePrescriptionFileNameParams) error
	UpdatePrescriptionOCRStatus(ctx context.Context, arg UpdatePrescriptionOCRStatusParams) (int64, error)
	UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) (int64, error)
	UpsertDoctorSchedule(ctx context.Context, arg UpsertDoctorScheduleParams) (UpsertDoctorScheduleRow, error)
	UpsertMedicationLog(ctx context.Context, arg UpsertMedicationLogParams) (UpsertMedicationLogRow, error)
	UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error)
	VerifyPrescription(ctx context.Context, arg VerifyPrescriptionParams) (int64, error)
	VerifyPrescriptionItemOwnership(ctx context.Context, arg VerifyPrescriptionItemOwnershipParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
