// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDoctorScheduleByDay = `-- name: DeleteDoctorScheduleByDay :exec
DELETE FROM doctor_schedules
WHERE doctor_id = $1 AND day_of_week = $2 AND tenant_id = $3
`

type DeleteDoctorScheduleByDayParams struct {
	DoctorID  uuid.UUID `json:"doctor_id"`
	DayOfWeek int32     `json:"day_of_week"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDoctorScheduleByDay(ctx context.Context, arg DeleteDoctorScheduleByDayParams) error {
	_, err := q.db.Exec(ctx, deleteDoctorScheduleByDay, arg.DoctorID, arg.DayOfWeek, arg.TenantID)
	return err
}

const getDoctorScheduleByDay = `-- name: GetDoctorScheduleByDay :one
SELECT id, doctor_id, day_of_week, start_time, end_time, slot_duration, timezone, is_active, created_at, updated_at
FROM doctor_schedules
WHERE doctor_id = $1 AND day_of_week = $2 AND tenant_id = $3
`

type GetDoctorScheduleByDayParams struct {
	DoctorID  uuid.UUID `json:"doctor_id"`
	DayOfWeek int32     `json:"day_of_week"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

type GetDoctorScheduleByDayRow struct {
	ID           uuid.UUID          `json:"id"`
	DoctorID     uuid.UUID          `json:"doctor_id"`
	DayOfWeek    int32              `json:"day_of_week"`
	StartTime    pgtype.Time        `json:"start_time"`
	EndTime      pgtype.Time        `json:"end_time"`
	SlotDuration int32              `json:"slot_duration"`
	Timezone     string             `json:"timezone"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDoctorScheduleByDay(ctx context.Context, arg GetDoctorScheduleByDayParams) (GetDoctorScheduleByDayRow, error) {
	row := q.db.QueryRow(ctx, getDoctorScheduleByDay, arg.DoctorID, arg.DayOfWeek, arg.TenantID)
	var i GetDoctorScheduleByDayRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.SlotDuration,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorSchedules = `-- name: GetDoctorSchedules :many
SELECT id, doctor_id, day_of_week, start_time, end_time, slot_duration, timezone, is_active, created_at, updated_at
FROM doctor_schedules
WHERE doctor_id = $1 AND tenant_id = $2
ORDER BY day_of_week ASC
`

type GetDoctorSchedulesParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDoctorSchedulesRow struct {
	ID           uuid.UUID          `json:"id"`
	DoctorID     uuid.UUID          `json:"doctor_id"`
	DayOfWeek    int32              `json:"day_of_week"`
	StartTime    pgtype.Time        `json:"start_time"`
	EndTime      pgtype.Time        `json:"end_time"`
	SlotDuration int32              `json:"slot_duration"`
	Timezone     string             `json:"timezone"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDoctorSchedules(ctx context.Context, arg GetDoctorSchedulesParams) ([]GetDoctorSchedulesRow, error) {
	rows, err := q.db.Query(ctx, getDoctorSchedules, arg.DoctorID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDoctorSchedulesRow{}
	for rows.Next() {
		var i GetDoctorSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotDuration,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDoctorSchedule = `-- name: UpsertDoctorSchedule :one
INSERT INTO doctor_schedules (doctor_id, day_of_week, start_time, end_time, slot_duration, timezone, is_active, updated_at, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), $8)
ON CONFLICT (doctor_id, day_of_week) 
DO UPDATE SET
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    slot_duration = EXCLUDED.slot_duration,
    timezone = EXCLUDED.timezone,
    is_active = EXCLUDED.is_active,
    updated_at = now()
RETURNING id, doctor_id, day_of_week, start_time, end_time, slot_duration, timezone, is_active, created_at, updated_at
`

type UpsertDoctorScheduleParams struct {
	DoctorID     uuid.UUID   `json:"doctor_id"`
	DayOfWeek    int32       `json:"day_of_week"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
	SlotDuration int32       `json:"slot_duration"`
	Timezone     string      `json:"timezone"`
	IsActive     pgtype.Bool `json:"is_active"`
	TenantID     uuid.UUID   `json:"tenant_id"`
}

type UpsertDoctorScheduleRow struct {
	ID           uuid.UUID          `json:"id"`
	DoctorID     uuid.UUID          `json:"doctor_id"`
	DayOfWeek    int32              `json:"day_of_week"`
	StartTime    pgtype.Time        `json:"start_time"`
	EndTime      pgtype.Time        `json:"end_time"`
	SlotDuration int32              `json:"slot_duration"`
	Timezone     string             `json:"timezone"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertDoctorSchedule(ctx context.Context, arg UpsertDoctorScheduleParams) (UpsertDoctorScheduleRow, error) {
	row := q.db.QueryRow(ctx, upsertDoctorSchedule,
		arg.DoctorID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.SlotDuration,
		arg.Timezone,
		arg.IsActive,
		arg.TenantID,
	)
	var i UpsertDoctorScheduleRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.SlotDuration,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
