// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, domain, status)
VALUES ($1, $2, 'active')
RETURNING id, name, domain, status, created_at, updated_at
`

type CreateTenantParams struct {
	Name   string      `json:"name"`
	Domain pgtype.Text `json:"domain"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantInvite = `-- name: CreateTenantInvite :one
INSERT INTO tenant_invites (tenant_id, invite_code, role, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, invite_code, role, expires_at, created_at
`

type CreateTenantInviteParams struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	InviteCode string             `json:"invite_code"`
	Role       string             `json:"role"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTenantInvite(ctx context.Context, arg CreateTenantInviteParams) (TenantInvite, error) {
	row := q.db.QueryRow(ctx, createTenantInvite,
		arg.TenantID,
		arg.InviteCode,
		arg.Role,
		arg.ExpiresAt,
	)
	var i TenantInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InviteCode,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTenantInvite = `-- name: DeleteTenantInvite :exec
DELETE FROM tenant_invites
WHERE invite_code = $1
`

func (q *Queries) DeleteTenantInvite(ctx context.Context, inviteCode string) error {
	_, err := q.db.Exec(ctx, deleteTenantInvite, inviteCode)
	return err
}

const getTenantInviteByCode = `-- name: GetTenantInviteByCode :one
SELECT id, tenant_id, invite_code, role, expires_at, created_at
FROM tenant_invites
WHERE invite_code = $1
`

func (q *Queries) GetTenantInviteByCode(ctx context.Context, inviteCode string) (TenantInvite, error) {
	row := q.db.QueryRow(ctx, getTenantInviteByCode, inviteCode)
	var i TenantInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InviteCode,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
