services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vital-watch-api
    restart: unless-stopped
    ports:
      - "8000:8080" # Map host port 8000 to container port 8080
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/app/storage
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: node:20-alpine
    container_name: vital-watch-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev

  db:
    image: postgres:15-alpine
    container_name: vital-watch-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - vital-watch-db-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v3.15.0
    container_name: vital-watch-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./backend/provisioning/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'

  grafana:
    image: grafana/grafana:13.2.3
    container_name: vital-watch-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend/provisioning/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:3.7.0
    container_name: vital-watch-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/tmp/loki

  alloy:
    image: grafana/alloy:v1.20.0
    container_name: vital-watch-alloy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.16.0
    container_name: vital-watch-postgres-exporter
    restart: unless-stopped
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://appuser:apppassword@db:5432/appdb?sslmode=disable"
    depends_on:
      - db

volumes:
  vital-watch-db-data:
  prometheus-data:
  grafana-data:
  loki-data:
