// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminProfile = `-- name: CreateAdminProfile :exec
INSERT INTO admin_profiles (user_id, first_name, last_name, department)
VALUES ($1, $2, $3, $4)
`

type CreateAdminProfileParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) CreateAdminProfile(ctx context.Context, arg CreateAdminProfileParams) error {
	_, err := q.db.Exec(ctx, createAdminProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Department,
	)
	return err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (email, hashed_password, role)
VALUES ($1, $2, 'admin')
RETURNING id
`

type CreateAdminUserParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Email, arg.HashedPassword)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT u.id, u.email, a.first_name, a.last_name, a.department, u.hashed_password, u.role, u.created_at
FROM users u
JOIN admin_profiles a ON u.id = a.user_id
WHERE u.email = $1 AND u.role = 'admin' AND u.is_active = true
`

type GetAdminByEmailRow struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Department     pgtype.Text        `json:"department"`
	HashedPassword string             `json:"hashed_password"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (GetAdminByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i GetAdminByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Department,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT u.id, u.email, a.first_name, a.last_name, a.department, u.role, u.created_at
FROM users u
JOIN admin_profiles a ON u.id = a.user_id
WHERE u.id = $1 AND u.role = 'admin' AND u.is_active = true
`

type GetAdminByIDRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	Department pgtype.Text        `json:"department"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (GetAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i GetAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Department,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT u.id, u.email, u.role, u.is_active, u.created_at
FROM users u
ORDER BY u.created_at DESC, u.id DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserActiveStatus = `-- name: UpdateUserActiveStatus :execrows
UPDATE users
SET is_active = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserActiveStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserActiveStatus, arg.ID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
