// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (patient_id, doctor_id, start_time, end_time, appointment_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateAppointmentParams struct {
	PatientID       uuid.UUID      `json:"patient_id"`
	DoctorID        uuid.UUID      `json:"doctor_id"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	AppointmentType sql.NullString `json:"appointment_type"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.PatientID,
		arg.DoctorID,
		arg.StartTime,
		arg.EndTime,
		arg.AppointmentType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAppointmentsByDoctorID = `-- name: GetAppointmentsByDoctorID :many
SELECT 
    a.id, a.patient_id, a.doctor_id, a.start_time, a.end_time, a.status, a.appointment_type, a.created_at,
    p.first_name, p.last_name
FROM appointments a
JOIN patient_profiles p ON a.patient_id = p.user_id
WHERE a.doctor_id = $1
ORDER BY a.start_time DESC
LIMIT $2 OFFSET $3
`

type GetAppointmentsByDoctorIDParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetAppointmentsByDoctorIDRow struct {
	ID              uuid.UUID      `json:"id"`
	PatientID       uuid.UUID      `json:"patient_id"`
	DoctorID        uuid.UUID      `json:"doctor_id"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	Status          sql.NullString `json:"status"`
	AppointmentType sql.NullString `json:"appointment_type"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
}

func (q *Queries) GetAppointmentsByDoctorID(ctx context.Context, arg GetAppointmentsByDoctorIDParams) ([]GetAppointmentsByDoctorIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsByDoctorID, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsByDoctorIDRow{}
	for rows.Next() {
		var i GetAppointmentsByDoctorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AppointmentType,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByPatientID = `-- name: GetAppointmentsByPatientID :many
SELECT 
    a.id, a.patient_id, a.doctor_id, a.start_time, a.end_time, a.status, a.appointment_type, a.created_at,
    d.first_name, d.last_name, d.specialty
FROM appointments a
JOIN doctor_profiles d ON a.doctor_id = d.user_id
WHERE a.patient_id = $1
ORDER BY a.start_time DESC
LIMIT $2 OFFSET $3
`

type GetAppointmentsByPatientIDParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetAppointmentsByPatientIDRow struct {
	ID              uuid.UUID      `json:"id"`
	PatientID       uuid.UUID      `json:"patient_id"`
	DoctorID        uuid.UUID      `json:"doctor_id"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	Status          sql.NullString `json:"status"`
	AppointmentType sql.NullString `json:"appointment_type"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Specialty       sql.NullString `json:"specialty"`
}

func (q *Queries) GetAppointmentsByPatientID(ctx context.Context, arg GetAppointmentsByPatientIDParams) ([]GetAppointmentsByPatientIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsByPatientID, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsByPatientIDRow{}
	for rows.Next() {
		var i GetAppointmentsByPatientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AppointmentType,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsForPatient = `-- name: GetAppointmentsForPatient :many
SELECT 
    a.id, a.patient_id, a.doctor_id, a.start_time, a.end_time, a.status, a.appointment_type, a.created_at,
    d.first_name, d.last_name, d.specialty
FROM appointments a
JOIN doctor_profiles d ON a.doctor_id = d.user_id
WHERE a.patient_id = $1 AND a.doctor_id = $2
ORDER BY a.start_time DESC
LIMIT $3 OFFSET $4
`

type GetAppointmentsForPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	DoctorID  uuid.UUID `json:"doctor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetAppointmentsForPatientRow struct {
	ID              uuid.UUID      `json:"id"`
	PatientID       uuid.UUID      `json:"patient_id"`
	DoctorID        uuid.UUID      `json:"doctor_id"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	Status          sql.NullString `json:"status"`
	AppointmentType sql.NullString `json:"appointment_type"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Specialty       sql.NullString `json:"specialty"`
}

func (q *Queries) GetAppointmentsForPatient(ctx context.Context, arg GetAppointmentsForPatientParams) ([]GetAppointmentsForPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsForPatient,
		arg.PatientID,
		arg.DoctorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsForPatientRow{}
	for rows.Next() {
		var i GetAppointmentsForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AppointmentType,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentAsCompletedForDoctor = `-- name: UpdateAppointmentAsCompletedForDoctor :execrows
UPDATE appointments 
SET status = 'completed' 
WHERE id = $1 AND doctor_id = $2
`

type UpdateAppointmentAsCompletedForDoctorParams struct {
	ID       uuid.UUID `json:"id"`
	DoctorID uuid.UUID `json:"doctor_id"`
}

func (q *Queries) UpdateAppointmentAsCompletedForDoctor(ctx context.Context, arg UpdateAppointmentAsCompletedForDoctorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAppointmentAsCompletedForDoctor, arg.ID, arg.DoctorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
