// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (id, patient_id, doctor_id, start_time, end_time, appointment_type, meeting_link, meeting_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateAppointmentParams struct {
	ID              uuid.UUID          `json:"id"`
	PatientID       uuid.UUID          `json:"patient_id"`
	DoctorID        uuid.UUID          `json:"doctor_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	MeetingLink     pgtype.Text        `json:"meeting_link"`
	MeetingID       pgtype.Text        `json:"meeting_id"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ID,
		arg.PatientID,
		arg.DoctorID,
		arg.StartTime,
		arg.EndTime,
		arg.AppointmentType,
		arg.MeetingLink,
		arg.MeetingID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT 
    a.id, a.patient_id, a.doctor_id, a.start_time, a.end_time, a.status, a.appointment_type, 
    a.meeting_link, a.meeting_id, a.created_at,
    d.first_name AS doctor_first_name, d.last_name AS doctor_last_name, d.specialty AS doctor_specialty,
    p.first_name AS patient_first_name, p.last_name AS patient_last_name
FROM appointments a
JOIN doctor_profiles d ON a.doctor_id = d.user_id
JOIN patient_profiles p ON a.patient_id = p.user_id
WHERE a.id = $1
`

type GetAppointmentByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	PatientID        uuid.UUID          `json:"patient_id"`
	DoctorID         uuid.UUID          `json:"doctor_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	Status           pgtype.Text        `json:"status"`
	AppointmentType  pgtype.Text        `json:"appointment_type"`
	MeetingLink      pgtype.Text        `json:"meeting_link"`
	MeetingID        pgtype.Text        `json:"meeting_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DoctorFirstName  string             `json:"doctor_first_name"`
	DoctorLastName   string             `json:"doctor_last_name"`
	DoctorSpecialty  pgtype.Text        `json:"doctor_specialty"`
	PatientFirstName string             `json:"patient_first_name"`
	PatientLastName  string             `json:"patient_last_name"`
}

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (GetAppointmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i GetAppointmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.AppointmentType,
		&i.MeetingLink,
		&i.MeetingID,
		&i.CreatedAt,
		&i.DoctorFirstName,
		&i.DoctorLastName,
		&i.DoctorSpecialty,
		&i.PatientFirstName,
		&i.PatientLastName,
	)
	return i, err
}

const getAppointmentsByDoctorID = `-- name: GetAppointmentsByDoctorID :many
SELECT 
    a.id, a.patient_id, a.doctor_id, a.start_time, a.end_time, a.status, a.appointment_type, 
    a.meeting_link, a.meeting_id, a.created_at,
    p.first_name, p.last_name
FROM appointments a
JOIN patient_profiles p ON a.patient_id = p.user_id
WHERE a.doctor_id = $1
ORDER BY a.start_time DESC
LIMIT $2 OFFSET $3
`

type GetAppointmentsByDoctorIDParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetAppointmentsByDoctorIDRow struct {
	ID              uuid.UUID          `json:"id"`
	PatientID       uuid.UUID          `json:"patient_id"`
	DoctorID        uuid.UUID          `json:"doctor_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Status          pgtype.Text        `json:"status"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	MeetingLink     pgtype.Text        `json:"meeting_link"`
	MeetingID       pgtype.Text        `json:"meeting_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
}

func (q *Queries) GetAppointmentsByDoctorID(ctx context.Context, arg GetAppointmentsByDoctorIDParams) ([]GetAppointmentsByDoctorIDRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByDoctorID, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsByDoctorIDRow{}
	for rows.Next() {
		var i GetAppointmentsByDoctorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AppointmentType,
			&i.MeetingLink,
			&i.MeetingID,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByPatientID = `-- name: GetAppointmentsByPatientID :many
SELECT 
    a.id, a.patient_id, a.doctor_id, a.start_time, a.end_time, a.status, a.appointment_type, 
    a.meeting_link, a.meeting_id, a.created_at,
    d.first_name, d.last_name, d.specialty
FROM appointments a
JOIN doctor_profiles d ON a.doctor_id = d.user_id
WHERE a.patient_id = $1
ORDER BY a.start_time DESC
LIMIT $2 OFFSET $3
`

type GetAppointmentsByPatientIDParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetAppointmentsByPatientIDRow struct {
	ID              uuid.UUID          `json:"id"`
	PatientID       uuid.UUID          `json:"patient_id"`
	DoctorID        uuid.UUID          `json:"doctor_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Status          pgtype.Text        `json:"status"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	MeetingLink     pgtype.Text        `json:"meeting_link"`
	MeetingID       pgtype.Text        `json:"meeting_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Specialty       pgtype.Text        `json:"specialty"`
}

func (q *Queries) GetAppointmentsByPatientID(ctx context.Context, arg GetAppointmentsByPatientIDParams) ([]GetAppointmentsByPatientIDRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByPatientID, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsByPatientIDRow{}
	for rows.Next() {
		var i GetAppointmentsByPatientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AppointmentType,
			&i.MeetingLink,
			&i.MeetingID,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsForPatient = `-- name: GetAppointmentsForPatient :many
SELECT 
    a.id, a.patient_id, a.doctor_id, a.start_time, a.end_time, a.status, a.appointment_type, 
    a.meeting_link, a.meeting_id, a.created_at,
    d.first_name, d.last_name, d.specialty
FROM appointments a
JOIN doctor_profiles d ON a.doctor_id = d.user_id
WHERE a.patient_id = $1 AND a.doctor_id = $2
ORDER BY a.start_time DESC
LIMIT $3 OFFSET $4
`

type GetAppointmentsForPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	DoctorID  uuid.UUID `json:"doctor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetAppointmentsForPatientRow struct {
	ID              uuid.UUID          `json:"id"`
	PatientID       uuid.UUID          `json:"patient_id"`
	DoctorID        uuid.UUID          `json:"doctor_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Status          pgtype.Text        `json:"status"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	MeetingLink     pgtype.Text        `json:"meeting_link"`
	MeetingID       pgtype.Text        `json:"meeting_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Specialty       pgtype.Text        `json:"specialty"`
}

func (q *Queries) GetAppointmentsForPatient(ctx context.Context, arg GetAppointmentsForPatientParams) ([]GetAppointmentsForPatientRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsForPatient,
		arg.PatientID,
		arg.DoctorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsForPatientRow{}
	for rows.Next() {
		var i GetAppointmentsForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AppointmentType,
			&i.MeetingLink,
			&i.MeetingID,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDoctorAppointmentsInRange = `-- name: GetDoctorAppointmentsInRange :many
SELECT a.id, a.doctor_id, a.start_time, a.end_time, a.status
FROM appointments a
WHERE a.doctor_id = $1 
  AND a.status != 'cancelled'
  AND a.start_time < $2::timestamptz 
  AND a.end_time > $3::timestamptz
ORDER BY a.start_time ASC
`

type GetDoctorAppointmentsInRangeParams struct {
	DoctorID   uuid.UUID          `json:"doctor_id"`
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
	RangeStart pgtype.Timestamptz `json:"range_start"`
}

type GetDoctorAppointmentsInRangeRow struct {
	ID        uuid.UUID          `json:"id"`
	DoctorID  uuid.UUID          `json:"doctor_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Status    pgtype.Text        `json:"status"`
}

func (q *Queries) GetDoctorAppointmentsInRange(ctx context.Context, arg GetDoctorAppointmentsInRangeParams) ([]GetDoctorAppointmentsInRangeRow, error) {
	rows, err := q.db.Query(ctx, getDoctorAppointmentsInRange, arg.DoctorID, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDoctorAppointmentsInRangeRow{}
	for rows.Next() {
		var i GetDoctorAppointmentsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentAsCompletedForDoctor = `-- name: UpdateAppointmentAsCompletedForDoctor :execrows
UPDATE appointments 
SET status = 'completed' 
WHERE id = $1 AND doctor_id = $2
`

type UpdateAppointmentAsCompletedForDoctorParams struct {
	ID       uuid.UUID `json:"id"`
	DoctorID uuid.UUID `json:"doctor_id"`
}

func (q *Queries) UpdateAppointmentAsCompletedForDoctor(ctx context.Context, arg UpdateAppointmentAsCompletedForDoctorParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppointmentAsCompletedForDoctor, arg.ID, arg.DoctorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAppointmentMeetingRoom = `-- name: UpdateAppointmentMeetingRoom :exec
UPDATE appointments 
SET meeting_link = $1, meeting_id = $2
WHERE id = $3 AND (meeting_link IS NULL OR meeting_link = '')
`

type UpdateAppointmentMeetingRoomParams struct {
	MeetingLink pgtype.Text `json:"meeting_link"`
	MeetingID   pgtype.Text `json:"meeting_id"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateAppointmentMeetingRoom(ctx context.Context, arg UpdateAppointmentMeetingRoomParams) error {
	_, err := q.db.Exec(ctx, updateAppointmentMeetingRoom, arg.MeetingLink, arg.MeetingID, arg.ID)
	return err
}
