// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO phi_audit_logs (
    user_id, user_role, action, resource_type, resource_id, patient_id, 
    ip_address, user_agent, request_id, status_code, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, user_role, action, resource_type, resource_id, patient_id, 
    ip_address, user_agent, request_id, status_code, metadata, created_at
`

type CreateAuditLogParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	UserRole     pgtype.Text `json:"user_role"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	PatientID    pgtype.UUID `json:"patient_id"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	RequestID    pgtype.UUID `json:"request_id"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (PhiAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.UserRole,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.PatientID,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.StatusCode,
		arg.Metadata,
	)
	var i PhiAuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserRole,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.PatientID,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.StatusCode,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT id, user_id, user_role, action, resource_type, resource_id, patient_id, 
    ip_address, user_agent, request_id, status_code, metadata, created_at
FROM phi_audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]PhiAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhiAuditLog{}
	for rows.Next() {
		var i PhiAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.PatientID,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.StatusCode,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByPatientID = `-- name: GetAuditLogsByPatientID :many
SELECT id, user_id, user_role, action, resource_type, resource_id, patient_id, 
    ip_address, user_agent, request_id, status_code, metadata, created_at
FROM phi_audit_logs
WHERE patient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditLogsByPatientIDParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetAuditLogsByPatientID(ctx context.Context, arg GetAuditLogsByPatientIDParams) ([]PhiAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByPatientID, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhiAuditLog{}
	for rows.Next() {
		var i PhiAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.PatientID,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.StatusCode,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
