// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctors.sql

package dbgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDoctorProfile = `-- name: CreateDoctorProfile :exec
INSERT INTO doctor_profiles (user_id, first_name, last_name, specialty, experience_years)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDoctorProfileParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Specialty       sql.NullString `json:"specialty"`
	ExperienceYears sql.NullInt32  `json:"experience_years"`
}

func (q *Queries) CreateDoctorProfile(ctx context.Context, arg CreateDoctorProfileParams) error {
	_, err := q.db.ExecContext(ctx, createDoctorProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Specialty,
		arg.ExperienceYears,
	)
	return err
}

const createDoctorUser = `-- name: CreateDoctorUser :one
INSERT INTO users (email, hashed_password, role)
VALUES ($1, $2, 'doctor')
RETURNING id
`

type CreateDoctorUserParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateDoctorUser(ctx context.Context, arg CreateDoctorUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDoctorUser, arg.Email, arg.HashedPassword)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDoctorByEmail = `-- name: GetDoctorByEmail :one
SELECT u.id, u.email, d.first_name, d.last_name, d.specialty, d.experience_years, d.available, u.hashed_password, u.created_at
FROM users u
JOIN doctor_profiles d ON u.id = d.user_id
WHERE u.email = $1 AND u.role = 'doctor' AND u.is_active = true
`

type GetDoctorByEmailRow struct {
	ID              uuid.UUID      `json:"id"`
	Email           string         `json:"email"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Specialty       sql.NullString `json:"specialty"`
	ExperienceYears sql.NullInt32  `json:"experience_years"`
	Available       sql.NullBool   `json:"available"`
	HashedPassword  string         `json:"hashed_password"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetDoctorByEmail(ctx context.Context, email string) (GetDoctorByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getDoctorByEmail, email)
	var i GetDoctorByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Specialty,
		&i.ExperienceYears,
		&i.Available,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT u.id, u.email, d.first_name, d.last_name, d.specialty, d.experience_years, d.available, u.created_at
FROM users u
JOIN doctor_profiles d ON u.id = d.user_id
WHERE u.id = $1 AND u.role = 'doctor' AND u.is_active = true
`

type GetDoctorByIDRow struct {
	ID              uuid.UUID      `json:"id"`
	Email           string         `json:"email"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Specialty       sql.NullString `json:"specialty"`
	ExperienceYears sql.NullInt32  `json:"experience_years"`
	Available       sql.NullBool   `json:"available"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetDoctorByID(ctx context.Context, id uuid.UUID) (GetDoctorByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDoctorByID, id)
	var i GetDoctorByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Specialty,
		&i.ExperienceYears,
		&i.Available,
		&i.CreatedAt,
	)
	return i, err
}

const getDoctors = `-- name: GetDoctors :many
SELECT u.id, u.email, d.first_name, d.last_name, d.specialty, d.experience_years, d.available, u.created_at
FROM users u
JOIN doctor_profiles d ON u.id = d.user_id
WHERE u.role = 'doctor' AND u.is_active = true
ORDER BY d.first_name ASC
LIMIT $1 OFFSET $2
`

type GetDoctorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetDoctorsRow struct {
	ID              uuid.UUID      `json:"id"`
	Email           string         `json:"email"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Specialty       sql.NullString `json:"specialty"`
	ExperienceYears sql.NullInt32  `json:"experience_years"`
	Available       sql.NullBool   `json:"available"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetDoctors(ctx context.Context, arg GetDoctorsParams) ([]GetDoctorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDoctors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDoctorsRow{}
	for rows.Next() {
		var i GetDoctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
			&i.ExperienceYears,
			&i.Available,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
