// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: medications.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActivePrescriptionItemsForPatient = `-- name: GetActivePrescriptionItemsForPatient :many
SELECT 
    pi.id, pi.prescription_id, pi.medication_name, pi.dosage, pi.frequency, pi.duration, pi.timing, pi.instructions, pi.created_at
FROM prescription_items pi
JOIN prescriptions p ON pi.prescription_id = p.id
WHERE p.patient_id = $1 
  AND p.status = 'approved'
  AND p.created_at < (date_trunc('day', $2::timestamptz) + interval '1 day')
  AND (p.expires_at IS NULL OR p.expires_at >= date_trunc('day', $2::timestamptz))
ORDER BY pi.created_at DESC
`

type GetActivePrescriptionItemsForPatientParams struct {
	PatientID  uuid.UUID          `json:"patient_id"`
	TargetDate pgtype.Timestamptz `json:"target_date"`
}

func (q *Queries) GetActivePrescriptionItemsForPatient(ctx context.Context, arg GetActivePrescriptionItemsForPatientParams) ([]PrescriptionItem, error) {
	rows, err := q.db.Query(ctx, getActivePrescriptionItemsForPatient, arg.PatientID, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrescriptionItem{}
	for rows.Next() {
		var i PrescriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionID,
			&i.MedicationName,
			&i.Dosage,
			&i.Frequency,
			&i.Duration,
			&i.Timing,
			&i.Instructions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMedicationLogsByDate = `-- name: GetMedicationLogsByDate :many
SELECT 
    l.id, l.patient_id, l.prescription_item_id, l.scheduled_date, l.time_of_day, l.dose_number, l.meal_timing, l.status, l.taken_at, l.notes, l.created_at,
    pi.medication_name, pi.dosage, pi.timing, pi.instructions
FROM patient_medication_logs l
JOIN prescription_items pi ON l.prescription_item_id = pi.id
WHERE l.patient_id = $1 AND l.scheduled_date = $2
ORDER BY l.created_at ASC
`

type GetMedicationLogsByDateParams struct {
	PatientID     uuid.UUID   `json:"patient_id"`
	ScheduledDate pgtype.Date `json:"scheduled_date"`
}

type GetMedicationLogsByDateRow struct {
	ID                 uuid.UUID          `json:"id"`
	PatientID          uuid.UUID          `json:"patient_id"`
	PrescriptionItemID uuid.UUID          `json:"prescription_item_id"`
	ScheduledDate      pgtype.Date        `json:"scheduled_date"`
	TimeOfDay          string             `json:"time_of_day"`
	DoseNumber         int32              `json:"dose_number"`
	MealTiming         pgtype.Text        `json:"meal_timing"`
	Status             string             `json:"status"`
	TakenAt            pgtype.Timestamptz `json:"taken_at"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	MedicationName     string             `json:"medication_name"`
	Dosage             pgtype.Text        `json:"dosage"`
	Timing             pgtype.Text        `json:"timing"`
	Instructions       pgtype.Text        `json:"instructions"`
}

func (q *Queries) GetMedicationLogsByDate(ctx context.Context, arg GetMedicationLogsByDateParams) ([]GetMedicationLogsByDateRow, error) {
	rows, err := q.db.Query(ctx, getMedicationLogsByDate, arg.PatientID, arg.ScheduledDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMedicationLogsByDateRow{}
	for rows.Next() {
		var i GetMedicationLogsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.PrescriptionItemID,
			&i.ScheduledDate,
			&i.TimeOfDay,
			&i.DoseNumber,
			&i.MealTiming,
			&i.Status,
			&i.TakenAt,
			&i.Notes,
			&i.CreatedAt,
			&i.MedicationName,
			&i.Dosage,
			&i.Timing,
			&i.Instructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMedicationLog = `-- name: UpsertMedicationLog :one
INSERT INTO patient_medication_logs (
    patient_id, prescription_item_id, scheduled_date, time_of_day, dose_number, meal_timing, status, taken_at, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (patient_id, prescription_item_id, scheduled_date, time_of_day, dose_number)
DO UPDATE SET
    status = EXCLUDED.status,
    taken_at = EXCLUDED.taken_at,
    notes = EXCLUDED.notes,
    meal_timing = COALESCE(EXCLUDED.meal_timing, patient_medication_logs.meal_timing)
RETURNING id, patient_id, prescription_item_id, scheduled_date, time_of_day, dose_number, meal_timing, status, taken_at, notes, created_at
`

type UpsertMedicationLogParams struct {
	PatientID          uuid.UUID          `json:"patient_id"`
	PrescriptionItemID uuid.UUID          `json:"prescription_item_id"`
	ScheduledDate      pgtype.Date        `json:"scheduled_date"`
	TimeOfDay          string             `json:"time_of_day"`
	DoseNumber         int32              `json:"dose_number"`
	MealTiming         pgtype.Text        `json:"meal_timing"`
	Status             string             `json:"status"`
	TakenAt            pgtype.Timestamptz `json:"taken_at"`
	Notes              pgtype.Text        `json:"notes"`
}

func (q *Queries) UpsertMedicationLog(ctx context.Context, arg UpsertMedicationLogParams) (PatientMedicationLog, error) {
	row := q.db.QueryRow(ctx, upsertMedicationLog,
		arg.PatientID,
		arg.PrescriptionItemID,
		arg.ScheduledDate,
		arg.TimeOfDay,
		arg.DoseNumber,
		arg.MealTiming,
		arg.Status,
		arg.TakenAt,
		arg.Notes,
	)
	var i PatientMedicationLog
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.PrescriptionItemID,
		&i.ScheduledDate,
		&i.TimeOfDay,
		&i.DoseNumber,
		&i.MealTiming,
		&i.Status,
		&i.TakenAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const verifyPrescriptionItemOwnership = `-- name: VerifyPrescriptionItemOwnership :one
SELECT COUNT(*) > 0 AS is_owner
FROM prescription_items pi
JOIN prescriptions p ON pi.prescription_id = p.id
WHERE pi.id = $1 AND p.patient_id = $2 AND p.status = 'approved'
`

type VerifyPrescriptionItemOwnershipParams struct {
	ID        uuid.UUID `json:"id"`
	PatientID uuid.UUID `json:"patient_id"`
}

func (q *Queries) VerifyPrescriptionItemOwnership(ctx context.Context, arg VerifyPrescriptionItemOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyPrescriptionItemOwnership, arg.ID, arg.PatientID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}
