// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              uuid.UUID          `json:"id"`
	DoctorID        uuid.UUID          `json:"doctor_id"`
	PatientID       uuid.UUID          `json:"patient_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Status          pgtype.Text        `json:"status"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MeetingLink     pgtype.Text        `json:"meeting_link"`
	MeetingID       pgtype.Text        `json:"meeting_id"`
}

type DoctorProfile struct {
	UserID          uuid.UUID   `json:"user_id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	Specialty       pgtype.Text `json:"specialty"`
	ExperienceYears pgtype.Int4 `json:"experience_years"`
	Available       pgtype.Bool `json:"available"`
}

type DoctorSchedule struct {
	ID           uuid.UUID          `json:"id"`
	DoctorID     uuid.UUID          `json:"doctor_id"`
	DayOfWeek    int32              `json:"day_of_week"`
	StartTime    pgtype.Time        `json:"start_time"`
	EndTime      pgtype.Time        `json:"end_time"`
	SlotDuration int32              `json:"slot_duration"`
	Timezone     string             `json:"timezone"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PatientMedicationLog struct {
	ID                 uuid.UUID          `json:"id"`
	PatientID          uuid.UUID          `json:"patient_id"`
	PrescriptionItemID uuid.UUID          `json:"prescription_item_id"`
	ScheduledDate      pgtype.Date        `json:"scheduled_date"`
	TimeOfDay          string             `json:"time_of_day"`
	DoseNumber         int32              `json:"dose_number"`
	MealTiming         pgtype.Text        `json:"meal_timing"`
	Status             string             `json:"status"`
	TakenAt            pgtype.Timestamptz `json:"taken_at"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PatientProfile struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

type PatientVital struct {
	ID               uuid.UUID          `json:"id"`
	PatientID        uuid.UUID          `json:"patient_id"`
	RecordedBy       uuid.UUID          `json:"recorded_by"`
	RecordedAt       pgtype.Timestamptz `json:"recorded_at"`
	SystolicBp       pgtype.Int4        `json:"systolic_bp"`
	DiastolicBp      pgtype.Int4        `json:"diastolic_bp"`
	HeartRate        pgtype.Int4        `json:"heart_rate"`
	BloodGlucose     pgtype.Numeric     `json:"blood_glucose"`
	OxygenSaturation pgtype.Numeric     `json:"oxygen_saturation"`
	Temperature      pgtype.Numeric     `json:"temperature"`
	WeightKg         pgtype.Numeric     `json:"weight_kg"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PhiAuditLog struct {
	ID           uuid.UUID          `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	UserRole     pgtype.Text        `json:"user_role"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	PatientID    pgtype.UUID        `json:"patient_id"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	RequestID    pgtype.UUID        `json:"request_id"`
	StatusCode   pgtype.Int4        `json:"status_code"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Prescription struct {
	ID          uuid.UUID          `json:"id"`
	PatientID   uuid.UUID          `json:"patient_id"`
	DoctorID    uuid.UUID          `json:"doctor_id"`
	Medication  pgtype.Text        `json:"medication"`
	Notes       pgtype.Text        `json:"notes"`
	FileName    pgtype.Text        `json:"file_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	OcrProvider pgtype.Text        `json:"ocr_provider"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type PrescriptionItem struct {
	ID             uuid.UUID          `json:"id"`
	PrescriptionID uuid.UUID          `json:"prescription_id"`
	MedicationName string             `json:"medication_name"`
	Dosage         pgtype.Text        `json:"dosage"`
	Frequency      pgtype.Text        `json:"frequency"`
	Duration       pgtype.Text        `json:"duration"`
	Timing         pgtype.Text        `json:"timing"`
	Instructions   pgtype.Text        `json:"instructions"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenID pgtype.UUID        `json:"replaced_by_token_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	Role           string             `json:"role"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
