// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID              uuid.UUID      `json:"id"`
	DoctorID        uuid.UUID      `json:"doctor_id"`
	PatientID       uuid.UUID      `json:"patient_id"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	Status          sql.NullString `json:"status"`
	AppointmentType sql.NullString `json:"appointment_type"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type DoctorProfile struct {
	UserID          uuid.UUID      `json:"user_id"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Specialty       sql.NullString `json:"specialty"`
	ExperienceYears sql.NullInt32  `json:"experience_years"`
	Available       sql.NullBool   `json:"available"`
}

type PatientProfile struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

type Prescription struct {
	ID         uuid.UUID      `json:"id"`
	PatientID  uuid.UUID      `json:"patient_id"`
	DoctorID   uuid.UUID      `json:"doctor_id"`
	Medication string         `json:"medication"`
	Notes      sql.NullString `json:"notes"`
	FileName   string         `json:"file_name"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type User struct {
	ID             uuid.UUID    `json:"id"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	Role           string       `json:"role"`
	IsActive       sql.NullBool `json:"is_active"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}
