// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              uuid.UUID          `json:"id"`
	DoctorID        uuid.UUID          `json:"doctor_id"`
	PatientID       uuid.UUID          `json:"patient_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Status          pgtype.Text        `json:"status"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DoctorProfile struct {
	UserID          uuid.UUID   `json:"user_id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	Specialty       pgtype.Text `json:"specialty"`
	ExperienceYears pgtype.Int4 `json:"experience_years"`
	Available       pgtype.Bool `json:"available"`
}

type PatientProfile struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

type Prescription struct {
	ID          uuid.UUID          `json:"id"`
	PatientID   uuid.UUID          `json:"patient_id"`
	DoctorID    uuid.UUID          `json:"doctor_id"`
	Medication  pgtype.Text        `json:"medication"`
	Notes       pgtype.Text        `json:"notes"`
	FileName    pgtype.Text        `json:"file_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	OcrProvider pgtype.Text        `json:"ocr_provider"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PrescriptionItem struct {
	ID             uuid.UUID          `json:"id"`
	PrescriptionID uuid.UUID          `json:"prescription_id"`
	MedicationName string             `json:"medication_name"`
	Dosage         pgtype.Text        `json:"dosage"`
	Frequency      pgtype.Text        `json:"frequency"`
	Duration       pgtype.Text        `json:"duration"`
	Timing         pgtype.Text        `json:"timing"`
	Instructions   pgtype.Text        `json:"instructions"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	Role           string             `json:"role"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
