// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: patients.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientProfile = `-- name: CreatePatientProfile :exec
INSERT INTO patient_profiles (user_id, first_name, last_name)
VALUES ($1, $2, $3)
`

type CreatePatientProfileParams struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) error {
	_, err := q.db.Exec(ctx, createPatientProfile, arg.UserID, arg.FirstName, arg.LastName)
	return err
}

const createPatientUser = `-- name: CreatePatientUser :one
INSERT INTO users (email, hashed_password, role)
VALUES ($1, $2, 'patient')
RETURNING id
`

type CreatePatientUserParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreatePatientUser(ctx context.Context, arg CreatePatientUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPatientUser, arg.Email, arg.HashedPassword)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPatientByEmail = `-- name: GetPatientByEmail :one
SELECT u.id, u.email, p.first_name, p.last_name, u.hashed_password, u.created_at
FROM users u
JOIN patient_profiles p ON u.id = p.user_id
WHERE u.email = $1 AND u.role = 'patient' AND u.is_active = true
`

type GetPatientByEmailRow struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPatientByEmail(ctx context.Context, email string) (GetPatientByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPatientByEmail, email)
	var i GetPatientByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT u.id, u.email, p.first_name, p.last_name, u.created_at
FROM users u
JOIN patient_profiles p ON u.id = p.user_id
WHERE u.id = $1 AND u.role = 'patient' AND u.is_active = true
`

type GetPatientByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPatientByID(ctx context.Context, id uuid.UUID) (GetPatientByIDRow, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i GetPatientByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getPatientsByDoctorID = `-- name: GetPatientsByDoctorID :many
SELECT DISTINCT u.id, u.email, p.first_name, p.last_name, u.created_at
FROM users u
JOIN patient_profiles p ON u.id = p.user_id
JOIN appointments a ON u.id = a.patient_id
WHERE a.doctor_id = $1
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPatientsByDoctorIDParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetPatientsByDoctorIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPatientsByDoctorID(ctx context.Context, arg GetPatientsByDoctorIDParams) ([]GetPatientsByDoctorIDRow, error) {
	rows, err := q.db.Query(ctx, getPatientsByDoctorID, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatientsByDoctorIDRow{}
	for rows.Next() {
		var i GetPatientsByDoctorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
