// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prescriptions.sql

package dbgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPrescription = `-- name: CreatePrescription :one
INSERT INTO prescriptions (patient_id, doctor_id, medication, notes, file_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreatePrescriptionParams struct {
	PatientID  uuid.UUID      `json:"patient_id"`
	DoctorID   uuid.UUID      `json:"doctor_id"`
	Medication string         `json:"medication"`
	Notes      sql.NullString `json:"notes"`
	FileName   string         `json:"file_name"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createPrescription,
		arg.PatientID,
		arg.DoctorID,
		arg.Medication,
		arg.Notes,
		arg.FileName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPrescriptionByFilename = `-- name: GetPrescriptionByFilename :one
SELECT id FROM prescriptions WHERE patient_id = $1 AND file_name = $2
`

type GetPrescriptionByFilenameParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	FileName  string    `json:"file_name"`
}

func (q *Queries) GetPrescriptionByFilename(ctx context.Context, arg GetPrescriptionByFilenameParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getPrescriptionByFilename, arg.PatientID, arg.FileName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPrescriptionByFilenameForDoctor = `-- name: GetPrescriptionByFilenameForDoctor :one
SELECT p.id 
FROM prescriptions p
LEFT JOIN appointments a ON p.patient_id = a.patient_id AND a.doctor_id = $2
WHERE p.file_name = $1 AND (p.doctor_id = $2 OR a.doctor_id = $2)
LIMIT 1
`

type GetPrescriptionByFilenameForDoctorParams struct {
	FileName string    `json:"file_name"`
	DoctorID uuid.UUID `json:"doctor_id"`
}

func (q *Queries) GetPrescriptionByFilenameForDoctor(ctx context.Context, arg GetPrescriptionByFilenameForDoctorParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getPrescriptionByFilenameForDoctor, arg.FileName, arg.DoctorID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPrescriptionsByPatientID = `-- name: GetPrescriptionsByPatientID :many
SELECT p.id, p.patient_id, p.doctor_id, p.medication, p.notes, p.file_name, p.created_at, d.first_name, d.last_name
FROM prescriptions p
JOIN doctor_profiles d ON p.doctor_id = d.user_id
WHERE p.patient_id = $1
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPrescriptionsByPatientIDParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetPrescriptionsByPatientIDRow struct {
	ID         uuid.UUID      `json:"id"`
	PatientID  uuid.UUID      `json:"patient_id"`
	DoctorID   uuid.UUID      `json:"doctor_id"`
	Medication string         `json:"medication"`
	Notes      sql.NullString `json:"notes"`
	FileName   string         `json:"file_name"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
}

func (q *Queries) GetPrescriptionsByPatientID(ctx context.Context, arg GetPrescriptionsByPatientIDParams) ([]GetPrescriptionsByPatientIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionsByPatientID, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPrescriptionsByPatientIDRow{}
	for rows.Next() {
		var i GetPrescriptionsByPatientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Medication,
			&i.Notes,
			&i.FileName,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionsForPatient = `-- name: GetPrescriptionsForPatient :many
SELECT 
    p.id, p.patient_id, p.doctor_id, p.medication, p.notes, p.file_name, p.created_at, 
    d.first_name, d.last_name
FROM prescriptions p
JOIN doctor_profiles d ON p.doctor_id = d.user_id
WHERE p.patient_id = $1 AND EXISTS (
    SELECT 1 FROM appointments a WHERE a.patient_id = $1 AND a.doctor_id = $2
)
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type GetPrescriptionsForPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	DoctorID  uuid.UUID `json:"doctor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetPrescriptionsForPatientRow struct {
	ID         uuid.UUID      `json:"id"`
	PatientID  uuid.UUID      `json:"patient_id"`
	DoctorID   uuid.UUID      `json:"doctor_id"`
	Medication string         `json:"medication"`
	Notes      sql.NullString `json:"notes"`
	FileName   string         `json:"file_name"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
}

func (q *Queries) GetPrescriptionsForPatient(ctx context.Context, arg GetPrescriptionsForPatientParams) ([]GetPrescriptionsForPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionsForPatient,
		arg.PatientID,
		arg.DoctorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPrescriptionsForPatientRow{}
	for rows.Next() {
		var i GetPrescriptionsForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Medication,
			&i.Notes,
			&i.FileName,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
