// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prescriptions.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDigitalPrescription = `-- name: CreateDigitalPrescription :one
INSERT INTO prescriptions (patient_id, doctor_id, source, status, notes)
VALUES ($1, $2, 'digital', 'approved', $3)
RETURNING id
`

type CreateDigitalPrescriptionParams struct {
	PatientID uuid.UUID   `json:"patient_id"`
	DoctorID  uuid.UUID   `json:"doctor_id"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) CreateDigitalPrescription(ctx context.Context, arg CreateDigitalPrescriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDigitalPrescription, arg.PatientID, arg.DoctorID, arg.Notes)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPrescription = `-- name: CreatePrescription :one
INSERT INTO prescriptions (patient_id, doctor_id, source, status, file_name, notes)
VALUES ($1, $2, 'uploaded', $3, $4, $5)
RETURNING id
`

type CreatePrescriptionParams struct {
	PatientID uuid.UUID   `json:"patient_id"`
	DoctorID  uuid.UUID   `json:"doctor_id"`
	Status    string      `json:"status"`
	FileName  pgtype.Text `json:"file_name"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPrescription,
		arg.PatientID,
		arg.DoctorID,
		arg.Status,
		arg.FileName,
		arg.Notes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePrescriptionItems = `-- name: DeletePrescriptionItems :exec
DELETE FROM prescription_items
WHERE prescription_id = $1
`

func (q *Queries) DeletePrescriptionItems(ctx context.Context, prescriptionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrescriptionItems, prescriptionID)
	return err
}

const getPrescriptionByFilename = `-- name: GetPrescriptionByFilename :one
SELECT id, status FROM prescriptions WHERE patient_id = $1 AND file_name = $2 AND status = 'approved'
`

type GetPrescriptionByFilenameParams struct {
	PatientID uuid.UUID   `json:"patient_id"`
	FileName  pgtype.Text `json:"file_name"`
}

type GetPrescriptionByFilenameRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) GetPrescriptionByFilename(ctx context.Context, arg GetPrescriptionByFilenameParams) (GetPrescriptionByFilenameRow, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByFilename, arg.PatientID, arg.FileName)
	var i GetPrescriptionByFilenameRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getPrescriptionByFilenameForDoctor = `-- name: GetPrescriptionByFilenameForDoctor :one
SELECT p.id, p.status
FROM prescriptions p
LEFT JOIN appointments a ON p.patient_id = a.patient_id AND a.doctor_id = $2
WHERE p.file_name = $1 AND (p.doctor_id = $2 OR a.doctor_id = $2)
LIMIT 1
`

type GetPrescriptionByFilenameForDoctorParams struct {
	FileName pgtype.Text `json:"file_name"`
	DoctorID uuid.UUID   `json:"doctor_id"`
}

type GetPrescriptionByFilenameForDoctorRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) GetPrescriptionByFilenameForDoctor(ctx context.Context, arg GetPrescriptionByFilenameForDoctorParams) (GetPrescriptionByFilenameForDoctorRow, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByFilenameForDoctor, arg.FileName, arg.DoctorID)
	var i GetPrescriptionByFilenameForDoctorRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getPrescriptionByID = `-- name: GetPrescriptionByID :one
SELECT
    p.id, p.patient_id, p.doctor_id, p.source, p.status, p.file_name, p.notes, p.ocr_provider, p.created_at, p.updated_at,
    d.first_name AS doctor_first_name, d.last_name AS doctor_last_name,
    pat.first_name AS patient_first_name, pat.last_name AS patient_last_name
FROM prescriptions p
JOIN doctor_profiles d ON p.doctor_id = d.user_id
JOIN patient_profiles pat ON p.patient_id = pat.user_id
WHERE p.id = $1
`

type GetPrescriptionByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	PatientID        uuid.UUID          `json:"patient_id"`
	DoctorID         uuid.UUID          `json:"doctor_id"`
	Source           string             `json:"source"`
	Status           string             `json:"status"`
	FileName         pgtype.Text        `json:"file_name"`
	Notes            pgtype.Text        `json:"notes"`
	OcrProvider      pgtype.Text        `json:"ocr_provider"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DoctorFirstName  string             `json:"doctor_first_name"`
	DoctorLastName   string             `json:"doctor_last_name"`
	PatientFirstName string             `json:"patient_first_name"`
	PatientLastName  string             `json:"patient_last_name"`
}

func (q *Queries) GetPrescriptionByID(ctx context.Context, id uuid.UUID) (GetPrescriptionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByID, id)
	var i GetPrescriptionByIDRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.Source,
		&i.Status,
		&i.FileName,
		&i.Notes,
		&i.OcrProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoctorFirstName,
		&i.DoctorLastName,
		&i.PatientFirstName,
		&i.PatientLastName,
	)
	return i, err
}

const getPrescriptionItemsByPrescriptionID = `-- name: GetPrescriptionItemsByPrescriptionID :many
SELECT id, prescription_id, medication_name, dosage, frequency, duration, timing, instructions, created_at
FROM prescription_items
WHERE prescription_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetPrescriptionItemsByPrescriptionID(ctx context.Context, prescriptionID uuid.UUID) ([]PrescriptionItem, error) {
	rows, err := q.db.Query(ctx, getPrescriptionItemsByPrescriptionID, prescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrescriptionItem{}
	for rows.Next() {
		var i PrescriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionID,
			&i.MedicationName,
			&i.Dosage,
			&i.Frequency,
			&i.Duration,
			&i.Timing,
			&i.Instructions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionItemsByPrescriptionIDs = `-- name: GetPrescriptionItemsByPrescriptionIDs :many
SELECT id, prescription_id, medication_name, dosage, frequency, duration, timing, instructions, created_at
FROM prescription_items
WHERE prescription_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) GetPrescriptionItemsByPrescriptionIDs(ctx context.Context, prescriptionIds []uuid.UUID) ([]PrescriptionItem, error) {
	rows, err := q.db.Query(ctx, getPrescriptionItemsByPrescriptionIDs, prescriptionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrescriptionItem{}
	for rows.Next() {
		var i PrescriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionID,
			&i.MedicationName,
			&i.Dosage,
			&i.Frequency,
			&i.Duration,
			&i.Timing,
			&i.Instructions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionsByPatientID = `-- name: GetPrescriptionsByPatientID :many
SELECT p.id, p.patient_id, p.doctor_id, p.source, p.status, p.file_name, p.notes, p.ocr_provider, p.created_at, p.updated_at, d.first_name, d.last_name
FROM prescriptions p
JOIN doctor_profiles d ON p.doctor_id = d.user_id
WHERE p.patient_id = $1
  AND p.status = 'approved'
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPrescriptionsByPatientIDParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetPrescriptionsByPatientIDRow struct {
	ID          uuid.UUID          `json:"id"`
	PatientID   uuid.UUID          `json:"patient_id"`
	DoctorID    uuid.UUID          `json:"doctor_id"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	FileName    pgtype.Text        `json:"file_name"`
	Notes       pgtype.Text        `json:"notes"`
	OcrProvider pgtype.Text        `json:"ocr_provider"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
}

func (q *Queries) GetPrescriptionsByPatientID(ctx context.Context, arg GetPrescriptionsByPatientIDParams) ([]GetPrescriptionsByPatientIDRow, error) {
	rows, err := q.db.Query(ctx, getPrescriptionsByPatientID, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPrescriptionsByPatientIDRow{}
	for rows.Next() {
		var i GetPrescriptionsByPatientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Source,
			&i.Status,
			&i.FileName,
			&i.Notes,
			&i.OcrProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionsForPatient = `-- name: GetPrescriptionsForPatient :many
SELECT
    p.id, p.patient_id, p.doctor_id, p.source, p.status, p.file_name, p.notes, p.ocr_provider, p.created_at, p.updated_at,
    d.first_name, d.last_name
FROM prescriptions p
JOIN doctor_profiles d ON p.doctor_id = d.user_id
WHERE p.patient_id = $1
  AND ($5::varchar IS NULL OR $5 = '' OR p.status = $5)
  AND (
    p.doctor_id = $2
    OR EXISTS (
      SELECT 1 FROM appointments a WHERE a.patient_id = $1 AND a.doctor_id = $2
    )
  )
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type GetPrescriptionsForPatientParams struct {
	PatientID uuid.UUID   `json:"patient_id"`
	DoctorID  uuid.UUID   `json:"doctor_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	Status    pgtype.Text `json:"status"`
}

type GetPrescriptionsForPatientRow struct {
	ID          uuid.UUID          `json:"id"`
	PatientID   uuid.UUID          `json:"patient_id"`
	DoctorID    uuid.UUID          `json:"doctor_id"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	FileName    pgtype.Text        `json:"file_name"`
	Notes       pgtype.Text        `json:"notes"`
	OcrProvider pgtype.Text        `json:"ocr_provider"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
}

func (q *Queries) GetPrescriptionsForPatient(ctx context.Context, arg GetPrescriptionsForPatientParams) ([]GetPrescriptionsForPatientRow, error) {
	rows, err := q.db.Query(ctx, getPrescriptionsForPatient,
		arg.PatientID,
		arg.DoctorID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPrescriptionsForPatientRow{}
	for rows.Next() {
		var i GetPrescriptionsForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Source,
			&i.Status,
			&i.FileName,
			&i.Notes,
			&i.OcrProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionsPendingReview = `-- name: GetPrescriptionsPendingReview :many
SELECT
    p.id, p.patient_id, p.doctor_id, p.source, p.status, p.file_name, p.notes, p.ocr_provider, p.created_at, p.updated_at,
    d.first_name AS doctor_first_name, d.last_name AS doctor_last_name,
    pat.first_name AS patient_first_name, pat.last_name AS patient_last_name
FROM prescriptions p
JOIN doctor_profiles d ON p.doctor_id = d.user_id
JOIN patient_profiles pat ON p.patient_id = pat.user_id
WHERE p.status = 'needs_review'
  AND (
    p.doctor_id = $1
    OR EXISTS (
      SELECT 1 FROM appointments a
      WHERE a.patient_id = p.patient_id AND a.doctor_id = $1
    )
  )
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPrescriptionsPendingReviewParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetPrescriptionsPendingReviewRow struct {
	ID               uuid.UUID          `json:"id"`
	PatientID        uuid.UUID          `json:"patient_id"`
	DoctorID         uuid.UUID          `json:"doctor_id"`
	Source           string             `json:"source"`
	Status           string             `json:"status"`
	FileName         pgtype.Text        `json:"file_name"`
	Notes            pgtype.Text        `json:"notes"`
	OcrProvider      pgtype.Text        `json:"ocr_provider"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DoctorFirstName  string             `json:"doctor_first_name"`
	DoctorLastName   string             `json:"doctor_last_name"`
	PatientFirstName string             `json:"patient_first_name"`
	PatientLastName  string             `json:"patient_last_name"`
}

func (q *Queries) GetPrescriptionsPendingReview(ctx context.Context, arg GetPrescriptionsPendingReviewParams) ([]GetPrescriptionsPendingReviewRow, error) {
	rows, err := q.db.Query(ctx, getPrescriptionsPendingReview, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPrescriptionsPendingReviewRow{}
	for rows.Next() {
		var i GetPrescriptionsPendingReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Source,
			&i.Status,
			&i.FileName,
			&i.Notes,
			&i.OcrProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoctorFirstName,
			&i.DoctorLastName,
			&i.PatientFirstName,
			&i.PatientLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPrescriptionItem = `-- name: InsertPrescriptionItem :one
INSERT INTO prescription_items (prescription_id, medication_name, dosage, frequency, duration, timing, instructions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, prescription_id, medication_name, dosage, frequency, duration, timing, instructions, created_at
`

type InsertPrescriptionItemParams struct {
	PrescriptionID uuid.UUID   `json:"prescription_id"`
	MedicationName string      `json:"medication_name"`
	Dosage         pgtype.Text `json:"dosage"`
	Frequency      pgtype.Text `json:"frequency"`
	Duration       pgtype.Text `json:"duration"`
	Timing         pgtype.Text `json:"timing"`
	Instructions   pgtype.Text `json:"instructions"`
}

func (q *Queries) InsertPrescriptionItem(ctx context.Context, arg InsertPrescriptionItemParams) (PrescriptionItem, error) {
	row := q.db.QueryRow(ctx, insertPrescriptionItem,
		arg.PrescriptionID,
		arg.MedicationName,
		arg.Dosage,
		arg.Frequency,
		arg.Duration,
		arg.Timing,
		arg.Instructions,
	)
	var i PrescriptionItem
	err := row.Scan(
		&i.ID,
		&i.PrescriptionID,
		&i.MedicationName,
		&i.Dosage,
		&i.Frequency,
		&i.Duration,
		&i.Timing,
		&i.Instructions,
		&i.CreatedAt,
	)
	return i, err
}

const updatePrescriptionOCRStatus = `-- name: UpdatePrescriptionOCRStatus :execrows
UPDATE prescriptions
SET status = $2,
    notes = CASE
        WHEN $3 IS NOT NULL AND notes IS NOT NULL AND notes <> '' THEN notes || E'\n' || $3
        WHEN $3 IS NOT NULL THEN $3
        ELSE notes
    END,
    ocr_provider = $4,
    updated_at = now()
WHERE id = $1
  AND status = 'pending_ocr'
`

type UpdatePrescriptionOCRStatusParams struct {
	ID          uuid.UUID   `json:"id"`
	Status      string      `json:"status"`
	Notes       pgtype.Text `json:"notes"`
	OcrProvider pgtype.Text `json:"ocr_provider"`
}

func (q *Queries) UpdatePrescriptionOCRStatus(ctx context.Context, arg UpdatePrescriptionOCRStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePrescriptionOCRStatus,
		arg.ID,
		arg.Status,
		arg.Notes,
		arg.OcrProvider,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const verifyPrescription = `-- name: VerifyPrescription :execrows
UPDATE prescriptions p
SET status = $2,
    notes = CASE
        WHEN $3 IS NOT NULL THEN $3
        WHEN $2 = 'approved' THEN TRIM(regexp_replace(COALESCE(notes, ''), E'\s*\[(OCR|Storage)[^\]]+\]', '', 'g'))
        ELSE notes
    END,
    updated_at = now()
WHERE p.id = $1
  AND p.status = 'needs_review'
  AND (
    p.doctor_id = $4
    OR EXISTS (
      SELECT 1 FROM appointments a
      WHERE a.patient_id = p.patient_id AND a.doctor_id = $4
    )
  )
`

type VerifyPrescriptionParams struct {
	ID       uuid.UUID   `json:"id"`
	Status   string      `json:"status"`
	Notes    pgtype.Text `json:"notes"`
	DoctorID uuid.UUID   `json:"doctor_id"`
}

func (q *Queries) VerifyPrescription(ctx context.Context, arg VerifyPrescriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, verifyPrescription,
		arg.ID,
		arg.Status,
		arg.Notes,
		arg.DoctorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
