// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (uuid.UUID, error)
	CreateDoctorProfile(ctx context.Context, arg CreateDoctorProfileParams) error
	CreateDoctorUser(ctx context.Context, arg CreateDoctorUserParams) (uuid.UUID, error)
	CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) error
	CreatePatientUser(ctx context.Context, arg CreatePatientUserParams) (uuid.UUID, error)
	CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (uuid.UUID, error)
	GetAppointmentsByDoctorID(ctx context.Context, arg GetAppointmentsByDoctorIDParams) ([]GetAppointmentsByDoctorIDRow, error)
	GetAppointmentsByPatientID(ctx context.Context, arg GetAppointmentsByPatientIDParams) ([]GetAppointmentsByPatientIDRow, error)
	GetAppointmentsForPatient(ctx context.Context, arg GetAppointmentsForPatientParams) ([]GetAppointmentsForPatientRow, error)
	GetDoctorByEmail(ctx context.Context, email string) (GetDoctorByEmailRow, error)
	GetDoctorByID(ctx context.Context, id uuid.UUID) (GetDoctorByIDRow, error)
	GetDoctors(ctx context.Context, arg GetDoctorsParams) ([]GetDoctorsRow, error)
	GetPatientByEmail(ctx context.Context, email string) (GetPatientByEmailRow, error)
	GetPatientByID(ctx context.Context, id uuid.UUID) (GetPatientByIDRow, error)
	GetPatientsByDoctorID(ctx context.Context, arg GetPatientsByDoctorIDParams) ([]GetPatientsByDoctorIDRow, error)
	GetPrescriptionByFilename(ctx context.Context, arg GetPrescriptionByFilenameParams) (uuid.UUID, error)
	GetPrescriptionByFilenameForDoctor(ctx context.Context, arg GetPrescriptionByFilenameForDoctorParams) (uuid.UUID, error)
	GetPrescriptionsByPatientID(ctx context.Context, arg GetPrescriptionsByPatientIDParams) ([]GetPrescriptionsByPatientIDRow, error)
	GetPrescriptionsForPatient(ctx context.Context, arg GetPrescriptionsForPatientParams) ([]GetPrescriptionsForPatientRow, error)
	UpdateAppointmentAsCompletedForDoctor(ctx context.Context, arg UpdateAppointmentAsCompletedForDoctorParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
