// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (uuid.UUID, error)
	CreateDigitalPrescription(ctx context.Context, arg CreateDigitalPrescriptionParams) (uuid.UUID, error)
	CreateDoctorProfile(ctx context.Context, arg CreateDoctorProfileParams) error
	CreateDoctorUser(ctx context.Context, arg CreateDoctorUserParams) (uuid.UUID, error)
	CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) error
	CreatePatientUser(ctx context.Context, arg CreatePatientUserParams) (uuid.UUID, error)
	CreatePatientVital(ctx context.Context, arg CreatePatientVitalParams) (PatientVital, error)
	CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (uuid.UUID, error)
	DeleteDoctorScheduleByDay(ctx context.Context, arg DeleteDoctorScheduleByDayParams) error
	DeletePrescriptionItems(ctx context.Context, prescriptionID uuid.UUID) error
	GetActivePrescriptionItemsForPatient(ctx context.Context, arg GetActivePrescriptionItemsForPatientParams) ([]PrescriptionItem, error)
	GetAppointmentByID(ctx context.Context, id uuid.UUID) (GetAppointmentByIDRow, error)
	GetAppointmentsByDoctorID(ctx context.Context, arg GetAppointmentsByDoctorIDParams) ([]GetAppointmentsByDoctorIDRow, error)
	GetAppointmentsByPatientID(ctx context.Context, arg GetAppointmentsByPatientIDParams) ([]GetAppointmentsByPatientIDRow, error)
	GetAppointmentsForPatient(ctx context.Context, arg GetAppointmentsForPatientParams) ([]GetAppointmentsForPatientRow, error)
	GetDoctorAppointmentsInRange(ctx context.Context, arg GetDoctorAppointmentsInRangeParams) ([]GetDoctorAppointmentsInRangeRow, error)
	GetDoctorByEmail(ctx context.Context, email string) (GetDoctorByEmailRow, error)
	GetDoctorByID(ctx context.Context, id uuid.UUID) (GetDoctorByIDRow, error)
	GetDoctorScheduleByDay(ctx context.Context, arg GetDoctorScheduleByDayParams) (DoctorSchedule, error)
	GetDoctorSchedules(ctx context.Context, doctorID uuid.UUID) ([]DoctorSchedule, error)
	GetDoctors(ctx context.Context, arg GetDoctorsParams) ([]GetDoctorsRow, error)
	GetLatestPatientVital(ctx context.Context, patientID uuid.UUID) (GetLatestPatientVitalRow, error)
	GetMedicationLogsByDate(ctx context.Context, arg GetMedicationLogsByDateParams) ([]GetMedicationLogsByDateRow, error)
	GetPatientByEmail(ctx context.Context, email string) (GetPatientByEmailRow, error)
	GetPatientByID(ctx context.Context, id uuid.UUID) (GetPatientByIDRow, error)
	GetPatientVitals(ctx context.Context, arg GetPatientVitalsParams) ([]GetPatientVitalsRow, error)
	GetPatientsByDoctorID(ctx context.Context, arg GetPatientsByDoctorIDParams) ([]GetPatientsByDoctorIDRow, error)
	GetPrescriptionByFilename(ctx context.Context, arg GetPrescriptionByFilenameParams) (GetPrescriptionByFilenameRow, error)
	GetPrescriptionByFilenameForDoctor(ctx context.Context, arg GetPrescriptionByFilenameForDoctorParams) (GetPrescriptionByFilenameForDoctorRow, error)
	GetPrescriptionByID(ctx context.Context, id uuid.UUID) (GetPrescriptionByIDRow, error)
	GetPrescriptionItemsByPrescriptionID(ctx context.Context, prescriptionID uuid.UUID) ([]PrescriptionItem, error)
	GetPrescriptionItemsByPrescriptionIDs(ctx context.Context, prescriptionIds []uuid.UUID) ([]PrescriptionItem, error)
	GetPrescriptionsByPatientID(ctx context.Context, arg GetPrescriptionsByPatientIDParams) ([]GetPrescriptionsByPatientIDRow, error)
	GetPrescriptionsForPatient(ctx context.Context, arg GetPrescriptionsForPatientParams) ([]GetPrescriptionsForPatientRow, error)
	GetPrescriptionsPendingReview(ctx context.Context, arg GetPrescriptionsPendingReviewParams) ([]GetPrescriptionsPendingReviewRow, error)
	HasDoctorPatientRelationship(ctx context.Context, arg HasDoctorPatientRelationshipParams) (pgtype.Bool, error)
	InsertPrescriptionItem(ctx context.Context, arg InsertPrescriptionItemParams) (PrescriptionItem, error)
	UpdateAppointmentAsCompletedForDoctor(ctx context.Context, arg UpdateAppointmentAsCompletedForDoctorParams) (int64, error)
	UpdateAppointmentMeetingRoom(ctx context.Context, arg UpdateAppointmentMeetingRoomParams) error
	UpdatePrescriptionOCRStatus(ctx context.Context, arg UpdatePrescriptionOCRStatusParams) (int64, error)
	UpsertDoctorSchedule(ctx context.Context, arg UpsertDoctorScheduleParams) (DoctorSchedule, error)
	UpsertMedicationLog(ctx context.Context, arg UpsertMedicationLogParams) (PatientMedicationLog, error)
	VerifyPrescription(ctx context.Context, arg VerifyPrescriptionParams) (int64, error)
	VerifyPrescriptionItemOwnership(ctx context.Context, arg VerifyPrescriptionItemOwnershipParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
