// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vitals.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientVital = `-- name: CreatePatientVital :one
INSERT INTO patient_vitals (
    patient_id, recorded_by, recorded_at, systolic_bp, diastolic_bp, heart_rate, 
    blood_glucose, oxygen_saturation, temperature, weight_kg, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, patient_id, recorded_by, recorded_at, systolic_bp, diastolic_bp, heart_rate, 
    blood_glucose, oxygen_saturation, temperature, weight_kg, notes, created_at
`

type CreatePatientVitalParams struct {
	PatientID        uuid.UUID          `json:"patient_id"`
	RecordedBy       uuid.UUID          `json:"recorded_by"`
	RecordedAt       pgtype.Timestamptz `json:"recorded_at"`
	SystolicBp       pgtype.Int4        `json:"systolic_bp"`
	DiastolicBp      pgtype.Int4        `json:"diastolic_bp"`
	HeartRate        pgtype.Int4        `json:"heart_rate"`
	BloodGlucose     pgtype.Numeric     `json:"blood_glucose"`
	OxygenSaturation pgtype.Numeric     `json:"oxygen_saturation"`
	Temperature      pgtype.Numeric     `json:"temperature"`
	WeightKg         pgtype.Numeric     `json:"weight_kg"`
	Notes            pgtype.Text        `json:"notes"`
}

func (q *Queries) CreatePatientVital(ctx context.Context, arg CreatePatientVitalParams) (PatientVital, error) {
	row := q.db.QueryRow(ctx, createPatientVital,
		arg.PatientID,
		arg.RecordedBy,
		arg.RecordedAt,
		arg.SystolicBp,
		arg.DiastolicBp,
		arg.HeartRate,
		arg.BloodGlucose,
		arg.OxygenSaturation,
		arg.Temperature,
		arg.WeightKg,
		arg.Notes,
	)
	var i PatientVital
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.SystolicBp,
		&i.DiastolicBp,
		&i.HeartRate,
		&i.BloodGlucose,
		&i.OxygenSaturation,
		&i.Temperature,
		&i.WeightKg,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPatientVital = `-- name: GetLatestPatientVital :one
SELECT 
    v.id, v.patient_id, v.recorded_by, v.recorded_at, v.systolic_bp, v.diastolic_bp, v.heart_rate, 
    v.blood_glucose, v.oxygen_saturation, v.temperature, v.weight_kg, v.notes, v.created_at,
    u.role AS recorder_role,
    COALESCE(dp.first_name, pp.first_name, '') AS recorder_first_name,
    COALESCE(dp.last_name, pp.last_name, '') AS recorder_last_name
FROM patient_vitals v
JOIN users u ON v.recorded_by = u.id
LEFT JOIN doctor_profiles dp ON u.id = dp.user_id
LEFT JOIN patient_profiles pp ON u.id = pp.user_id
WHERE v.patient_id = $1
ORDER BY v.recorded_at DESC
LIMIT 1
`

type GetLatestPatientVitalRow struct {
	ID                uuid.UUID          `json:"id"`
	PatientID         uuid.UUID          `json:"patient_id"`
	RecordedBy        uuid.UUID          `json:"recorded_by"`
	RecordedAt        pgtype.Timestamptz `json:"recorded_at"`
	SystolicBp        pgtype.Int4        `json:"systolic_bp"`
	DiastolicBp       pgtype.Int4        `json:"diastolic_bp"`
	HeartRate         pgtype.Int4        `json:"heart_rate"`
	BloodGlucose      pgtype.Numeric     `json:"blood_glucose"`
	OxygenSaturation  pgtype.Numeric     `json:"oxygen_saturation"`
	Temperature       pgtype.Numeric     `json:"temperature"`
	WeightKg          pgtype.Numeric     `json:"weight_kg"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RecorderRole      string             `json:"recorder_role"`
	RecorderFirstName string             `json:"recorder_first_name"`
	RecorderLastName  string             `json:"recorder_last_name"`
}

func (q *Queries) GetLatestPatientVital(ctx context.Context, patientID uuid.UUID) (GetLatestPatientVitalRow, error) {
	row := q.db.QueryRow(ctx, getLatestPatientVital, patientID)
	var i GetLatestPatientVitalRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.SystolicBp,
		&i.DiastolicBp,
		&i.HeartRate,
		&i.BloodGlucose,
		&i.OxygenSaturation,
		&i.Temperature,
		&i.WeightKg,
		&i.Notes,
		&i.CreatedAt,
		&i.RecorderRole,
		&i.RecorderFirstName,
		&i.RecorderLastName,
	)
	return i, err
}

const getPatientVitals = `-- name: GetPatientVitals :many
SELECT 
    v.id, v.patient_id, v.recorded_by, v.recorded_at, v.systolic_bp, v.diastolic_bp, v.heart_rate, 
    v.blood_glucose, v.oxygen_saturation, v.temperature, v.weight_kg, v.notes, v.created_at,
    u.role AS recorder_role,
    COALESCE(dp.first_name, pp.first_name, '') AS recorder_first_name,
    COALESCE(dp.last_name, pp.last_name, '') AS recorder_last_name
FROM patient_vitals v
JOIN users u ON v.recorded_by = u.id
LEFT JOIN doctor_profiles dp ON u.id = dp.user_id
LEFT JOIN patient_profiles pp ON u.id = pp.user_id
WHERE v.patient_id = $1
  AND ($4::timestamptz IS NULL OR v.recorded_at >= $4)
  AND ($5::timestamptz IS NULL OR v.recorded_at <= $5)
ORDER BY v.recorded_at DESC
LIMIT $2 OFFSET $3
`

type GetPatientVitalsParams struct {
	PatientID uuid.UUID          `json:"patient_id"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type GetPatientVitalsRow struct {
	ID                uuid.UUID          `json:"id"`
	PatientID         uuid.UUID          `json:"patient_id"`
	RecordedBy        uuid.UUID          `json:"recorded_by"`
	RecordedAt        pgtype.Timestamptz `json:"recorded_at"`
	SystolicBp        pgtype.Int4        `json:"systolic_bp"`
	DiastolicBp       pgtype.Int4        `json:"diastolic_bp"`
	HeartRate         pgtype.Int4        `json:"heart_rate"`
	BloodGlucose      pgtype.Numeric     `json:"blood_glucose"`
	OxygenSaturation  pgtype.Numeric     `json:"oxygen_saturation"`
	Temperature       pgtype.Numeric     `json:"temperature"`
	WeightKg          pgtype.Numeric     `json:"weight_kg"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RecorderRole      string             `json:"recorder_role"`
	RecorderFirstName string             `json:"recorder_first_name"`
	RecorderLastName  string             `json:"recorder_last_name"`
}

func (q *Queries) GetPatientVitals(ctx context.Context, arg GetPatientVitalsParams) ([]GetPatientVitalsRow, error) {
	rows, err := q.db.Query(ctx, getPatientVitals,
		arg.PatientID,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatientVitalsRow{}
	for rows.Next() {
		var i GetPatientVitalsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.RecordedBy,
			&i.RecordedAt,
			&i.SystolicBp,
			&i.DiastolicBp,
			&i.HeartRate,
			&i.BloodGlucose,
			&i.OxygenSaturation,
			&i.Temperature,
			&i.WeightKg,
			&i.Notes,
			&i.CreatedAt,
			&i.RecorderRole,
			&i.RecorderFirstName,
			&i.RecorderLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
